### ISSUE TITLE
settings.get(key) return null when called to quick in render

### ISSUE THREAD

**Issue by brendann993** [kettek/electron-app-settings#1]
My render calls `settings.get(key)` on window.DOMContentLoaded but it appears at this point the the render has not received the storage item via ipc channel 'configurator-master-set' yet and hence returns null even though the key exists in settings.

I solved this by waiting for `ipcRenderer.on('configurator-master-set',()=>{
});` before calling `settings.get(key)` but perhaps `settings.get()` could wait for the initial set before it returns any values?

**Comment by kettek** [comment]
It might be possible to rework the library or just add an API to use Promises so we can use async and await to resolve `settings.get()` and others. Async/await is fairly ubiquitous at this point so I think it'd work fine.

We could also add an event such as `configurator-ready` to have an explicit event that can be handled in the same way as you've done with `configurator-master-set`.

I'll do some tests over the week to see what the best choice might be. If you have any further thoughts, let me know.

**Comment by kettek** [comment]
Potentially electron-app-settings could expose a simple promise such as "settings.ready()" that one could use as such:

```
await settings.ready();

settings.get("myKey");
```

or

```
settings.ready()
.then(() => {
  settings.get("myKey");
})
.catch(err => {
  // ...
})
```

Otherwise every call to get/set *could* use Promises, although they'd always immediately resolve if the main settings has loaded. Examples:

```
let myKey = await settings.get("myKey");
// do something with myKey
```

or

```
settings.get("myKey")
.then((key, value) => {
  // do something with value
})
.catch(err => {
  // would this even be reachable?
})
```

This sort of change to get() would be quite significant and would result in a major version bump. At the moment I don't think it would make sense to replace the current get() functionality, although it wouldn't be too difficult to add asyncified functions such as `promiseGet()`/`promiseSet()` or `asyncGet()`/`asyncSet()`
