### ISSUE TITLE
bundled code fails on renderer initialization

### ISSUE THREAD

**Issue by bogenpirat** [kettek/electron-app-settings#4]
hey there,

i'm bundling my electron app which contains this package to handle settings with vue-cli-plugin-electron-builder which uses webpack to bundle js code.

i've noticed that my bundled/packaged code doesn't work and throws an exception like this:
![image](https://user-images.githubusercontent.com/1835496/103472159-5dd50800-4d8a-11eb-978d-43cd697054b3.png)

since this is an atypical error message, i've managed to trace the cause of this down to this line:
https://github.com/kettek/electron-app-settings/blob/ffd31351480079568c16d018b9223987d0d85945/lib/Renderer.js#L10
if i comment it out and just make sure that the main process has an instance of settings initialized, this error goes away and behavior is as expected.

does this qualify as a bug, or should i be trying to mess with webpack in order for this to be dynamically requirable?

**Comment by kettek** [comment]
It would seem some bundlers don't respect the use of remote.require per-default. This line exists solely to ensure that the main process has required the `electron-app-settings` module so that settings can be reliably saved from the renderer process. If the main process has already required the module(as you noticed), then this line does nothing. As such, this does not qualify as a bug, but rather as a problem in the domain of webpack.

However, it would be nice to be able to conditionally disable the `remote.require` line. I could add an environment variable check to disable the use of `remote.require`, with the caveat that the end-user would have to ensure that environment variable is set (via the invoking shell or through webpack's [DefinePlugin](https://github.com/webpack/docs/wiki/list-of-plugins#defineplugin)). Perhaps via an environment variable such as `NO_REMOTE_REQUIRE`?
